language: ruby
cache: bundler
sudo: false
env: RAILS_ENV=test
rvm: 2.2.1
before_script:
  - psql -c 'create database index_test;' -U postgres
script:
  - bundle exec rubocop
  - bundle exec rake db:migrate
  - bundle exec rspec -fd --color
deploy:
  provider: heroku
  api_key:
    secure: DMU5iIH2QnyHYfxtmsp+fKazZnTEo33sPgYzfaQoprS0y9jAFncqUFqDmcoqee5TY9+OjucSi0joF/sU+XK+peHSEyqYnP4GdhRqFKgylVmNhvvVeAnReTdxgJ3fsTXXmTh80gpPmum31tQ/arFTWJvSGpWaZMLkZaK/djSEyzY=
  app: theindex
  run: 'rake db:migrate'
