default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: <%= ENV.fetch('DB_1_PORT_5432_TCP_ADDR', 'localhost') %>
  port: <%= ENV.fetch('DB_1_PORT_5432_TCP_PORT', '5432') %>
  template: template0

development:
  <<: *default
  database: index_development

test:
  <<: *default
  database: index_test

production:
  <<: *default
  database: index_production
